name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ensure pnpm-workspace.yaml
        run: |
          if [ ! -f pnpm-workspace.yaml ]; then
            printf "packages:\n  - 'packages/*'\n" > pnpm-workspace.yaml
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
          cache: pnpm

      - name: Add Vitest devDependency
        run: pnpm add -Dw vitest@latest @vitest/coverage-v8

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run tests
        run: pnpm exec vitest run --run --passWithNoTests

      - name: Build declarations
        run: pnpm tsc --emitDeclarationOnly

      - name: Upload coverage report
        if: success() && matrix.node-version == '20.x'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: packages/**/coverage

      - name: Upload build artifacts
        if: success() && matrix.node-version == '20.x'
        uses: actions/upload-artifact@v4
        with:
          name: types
          path: dist/types