name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm lint

      - name: Run tests
        run: pnpm test

      - name: Build declarations
        run: pnpm tsc --emitDeclarationOnly

      - name: Upload coverage report
        if: success() && matrix.node-version == '18.x'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: packages/**/coverage

      - name: Upload build artifacts
        if: success() && matrix.node-version == '18.x'
        uses: actions/upload-artifact@v4
        with:
          name: types
          path: dist/types