name: Coverage
on:
  push:
    branches: [main]
  pull_request:
jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: Run tests with coverage (workspace)
        run: pnpm -r --filter './packages/*' --filter '!./site' --filter '!./packages/ui-react' vitest run --coverage
      - name: Upload to Codecov (OIDC, no token)
        if: ${{ hashFiles('packages/**/coverage/lcov.info') != '' }}
        uses: codecov/codecov-action@v4
        with:
          use_oidc: true
          files: "packages/**/coverage/lcov.info"
          fail_ci_if_error: true
          verbose: true
